name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn install -DskipTests

  test_JotterController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test JotterController
        run: mvn -Dtest=com.gm.wj.controller.JotterControllerTest test
  test_LibraryController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test LibraryController
        run: mvn -Dtest=com.gm.wj.controller.LibraryControllerTest test
  test_LoginController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test LoginController
        run: mvn -Dtest=com.gm.wj.controller.LoginControllerTest test
  test_RoleController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test RoleController
        run: mvn -Dtest=com.gm.wj.controller.RoleControllerTest test
  test_UserController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test UserController
        run: mvn -Dtest=com.gm.wj.controller.UserControllerTest test
