name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [6]
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306
        env:
          MYSQL_USER: aaa
          MYSQL_PASSWORD: aaa
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: aaa
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Verify mysql connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          sleep 1
          done
      - name: Initialize test database
        run: mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -u aaa -paaa test < src/main/resources/wj.sql
      - name: Build with Maven
        run: mvn install -DskipTests

  test_JotterController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test JotterController
        run: mvn -Dtest=com.gm.wj.controller.JotterControllerTest test
  test_LibraryController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test LibraryController
        run: mvn -Dtest=com.gm.wj.controller.LibraryControllerTest test
  test_LoginController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test LoginController
        run: mvn -Dtest=com.gm.wj.controller.LoginControllerTest test
  test_RoleController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test RoleController
        run: mvn -Dtest=com.gm.wj.controller.RoleControllerTest test
  test_UserController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test UserController
        run: mvn -Dtest=com.gm.wj.controller.UserControllerTest test
