name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn install
  test JotterController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test JotterController
        run: ./wj/controller/JotterControllerTest.java
  test LibraryController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test LibraryController
        run: src/test/java/wj/controller/JotterControllerTest.java
  test LoginController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test LoginController
        run: src/test/java/wj/controller/LoginControllerTest.java
  test RoleController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test RoleController
        run: src/test/java/wj/controller/RoleControllerTest.java
  test UserController:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test UserController
        run: src/test/java/wj/controller/UserControllerTest.java